name: Matrix Configuraiton

on:
  push:
  workflow_dispatch:

jobs:
  deploy-on-ubuntu:
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, windows-latest]
        images: [hello-world, alpine]
        exclude:
          - os: windows-latest
            images: apline
        include:
          - os: ubuntu-20.04
            images: amd64/alpine
    runs-on: ${{ matrix.os }}
    steps:
    - name: Echo Docker Details
      run: docker info
    - name: Run Images on ${{ matrix.os }}
      run: docker run ${{ matrix.images }}