name: Exploring variables and secrets

on: push


env:
  CONTAINER_REGISTRY: docker.io
  IMAGE_NAME: spring-hello

jobs: 
    docker:
      runs-on: ubuntu-latest
      steps:
      - name: Docker build
        run: echo docker build -t ${{ env.CONTAINER_REGISTRY }}/$DOCKER_USERNAME/${{ env.IMAGE_NAME}}:latest

      - name: Doker Login
        run: echo docker login --username=dockerUsername --password=${{ secrets.DOCKER_PASSWORD }}

      - name: Docker publish
        run: echo docker push ${{ env.CONTAINER_REGISTRY }}/$DOCKER_USERNAME/${{ env.IMAGE_NAME}}:latest

    deploy:
      needs: docker
      runs-on: ubuntu-latest
      steps:
      - name: Docker Run
        run: echo docker run -d -p 8080:80 ${{ env.CONTAINER_REGISTRY }}/$DOCKER_USERNAME/${{ env.IMAGE_NAME}}:latest