name: Exploring variables and secrets

on: push


env:
  CONTAINER_REGISTRY: docker.io
  IMAGE_NAME: spring-hello

jobs: 
    docker:
      runs-on: ubuntu_latest
      steps:
      - name: Docker build
        run: docker build -t ${{ env.CONTAINER_REGISTRY }}/$DOCKER_USERNAME/${{ env.IMAGE_NAME}}:latest

      - name: Doker Login
        run: docker login --username=dockerUsername --password=${{ secrets.DOCKER_PASSWORD }}

      - name: Docker publish
        run: docker push ${{ env.CONTAINER_REGISTRY }}/$DOCKER_USERNAME/${{ env.IMAGE_NAME}}:latest

    deploy:
      runs-on: ubuntu_latest
      steps:
      - name: Docker Run
        run: docker run -d -p 8080:80 ${{ env.CONTAINER_REGISTRY }}/$DOCKER_USERNAME/${{ env.IMAGE_NAME}}:latest